[package]
name = "local_ping_pong_openssl"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
# XXX XXX TBD XXX
# rustls = { version = "0.23.0", default-features = false, features = ["std"] }
# rustls = { version = "0.23.20", default-features = false, features = ["std"], git = "https://github.com/brodycj/rustls", branch = "portable-atomic-arc-option" }
rustls-rustcrypto = { path = "../../" }
openssl = { version = "0.10", default-features = false }
pem-rfc7468 = { version = "0.7", default-features = false, features = ["alloc"] }
# XXX TODO REMOVE - ONLY ADDED TO HELP FIX ISSUE WITH CARGO ADD
once_cell = { version = "1.20.3", default-features = false }
# XXX TODO MOVE TO BEGINNING OF THIS SECTION
rustls = { git = "https://github.com/brody4hire/portable-rustls", branch = "brody-switch-to-rc", version = "0.0.2-dev", package = "portable-rustls" }
